apiVersion: v1
kind: Service
metadata:
  name: db-internal-service
  namespace: appweb
selector:
  app: mariadb
spec:
  type: ClusterIP
  ports:
  - name: mariadb-port
    protocol: TCP
    port: 3306
    targetPort: 3306
    protocol: TCP
