apiVersion: v1
kind: Service
metadata:
  name: db-internal-service
  namespace: appweb
spec:
  selector:
#    app: mariadb
    run: mariadb
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
#  clusterIP: None
  type: NodePort
  
