apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: appweb
spec:
  selector:
    app: wordpress
#    run: wordpress
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080
  type: NodePort
