apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: appweb
selector:
  app: wordpress
spec:
#  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080
