apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deploy
  namespace: appweb
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb 
    spec: 
      containers:
      - name: mariadb
        image: mariadb
        args:
          - sleep
          - "100000"
        ports:
        - containerPort: 3306 #default one
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-root-password
        - name: MARIADB_DATABASE
          value: wordpress
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-volume
      volumes:
      - name: db-volume
        emptyDir: {}
